// src/seeds/sispro.references.seed.js
// Seed completo de tablas de referencia SISPRO
// Corrige datos incorrectos y carga tablas nuevas
// Uso: node src/seeds/sispro.references.seed.js
'use strict';

require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const { pool, testConnection } = require('../config/database');

// ─── Helper upsert ────────────────────────────────────────────────────────────
async function upsertAll(tabla, columnas, filas) {
  const cols   = columnas.join(', ');
  const params = columnas.map((_, i) => `$${i + 1}`).join(', ');
  const update = columnas.slice(1).map(c => `${c} = EXCLUDED.${c}`).join(', ');
  let inserted = 0, updated = 0;

  for (const fila of filas) {
    const res = await pool.query(
      `INSERT INTO ${tabla} (${cols}) VALUES (${params})
       ON CONFLICT (${columnas[0]})
       DO UPDATE SET ${update}
       RETURNING (xmax = 0) AS is_insert`,
      fila
    );
    if (res.rows[0].is_insert) inserted++; else updated++;
  }
  console.log(`  📋  ${tabla}: ${inserted} nuevos, ${updated} actualizados`);
}

// ─── Datos ────────────────────────────────────────────────────────────────────
const seeds = [

  // ── TABLAS EXISTENTES CORREGIDAS ──────────────────────────────────────────

  {
    tabla: 'ref_tipos_documento',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['AS', 'Adulto sin Identificación'],
      ['CC', 'Cédula de Ciudadanía'],
      ['CD', 'Carnet Diplomático'],
      ['CE', 'Cédula de Extranjería'],
      ['CN', 'Certificado de nacido vivo'],
      ['DE', 'Documento extranjero'],
      ['MS', 'Menor sin Identificación'],
      ['NV', 'Certificado de nacido vivo'],
      ['PA', 'Pasaporte'],
      ['PE', 'Permiso Especial de Permanencia'],
      ['PT', 'Permiso por Protección Temporal'],
      ['RC', 'Registro Civil'],
      ['SC', 'Salvoconducto'],
      ['SI', 'Sin Identificación'],
      ['TI', 'Tarjeta de Identidad'],
    ],
  },

  {
    tabla: 'ref_tipos_usuario',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Contributivo cotizante'],
      ['02', 'Contributivo beneficiario'],
      ['03', 'Contributivo adicional'],
      ['04', 'Subsidiado'],
      ['05', 'No afiliado'],
      ['06', 'Especial o Excepción cotizante'],
      ['07', 'Especial o Excepción beneficiario'],
      ['08', 'Personas privadas de la libertad a cargo del Fondo Nacional de Salud'],
      ['09', 'Tomador / Amparado ARL'],
      ['10', 'Tomador / Amparado SOAT'],
      ['11', 'Tomador / Amparado Planes voluntarios de salud'],
      ['12', 'Particular'],
      ['13', 'Especial o excepción no cotizante Ley 352 de 1997'],
    ],
  },

  {
    tabla: 'ref_modalidades',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Intramural'],
      ['02', 'Extramural unidad móvil'],
      ['03', 'Extramural domiciliaria'],
      ['04', 'Extramural jornada de salud'],
      ['06', 'Telemedicina interactiva'],
      ['07', 'Telemedicina no interactiva'],
      ['08', 'Telemedicina telexperticia'],
      ['09', 'Telemedicina telemonitoreo'],
    ],
  },

  {
    tabla: 'ref_grupos_servicio',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Consulta externa'],
      ['02', 'Apoyo diagnóstico y complementación terapéutica'],
      ['03', 'Internación'],
      ['04', 'Quirúrgico'],
      ['05', 'Atención inmediata'],
    ],
  },

  {
    tabla: 'ref_conceptos_recaudo',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Copago'],
      ['02', 'Cuota moderadora'],
      ['03', 'Pagos compartidos en planes voluntarios de salud'],
      ['05', 'No aplica'],
    ],
  },

  {
    tabla: 'ref_zonas_territoriales',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Rural'],
      ['02', 'Urbano'],
    ],
  },

  {
    tabla: 'ref_vias_ingreso',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Demanda espontánea'],
      ['02', 'Derivado de consulta externa'],
      ['03', 'Derivado de urgencias'],
      ['04', 'Derivado de hospitalización'],
      ['05', 'Derivado de sala de cirugía'],
      ['06', 'Derivado de sala de partos'],
      ['07', 'Recién nacido en la institución'],
      ['08', 'Recién nacido en otra institución'],
      ['09', 'Derivado o referido de hospitalización domiciliaria'],
      ['10', 'Derivado de atención domiciliaria'],
      ['11', 'Derivado de telemedicina'],
      ['12', 'Derivado de jornada de salud'],
      ['13', 'Referido de otra institución'],
      ['14', 'Contrareferido de otra institución'],
    ],
  },

  {
    tabla: 'ref_tipos_diagnostico',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Impresión diagnóstica'],
      ['02', 'Confirmado nuevo'],
      ['03', 'Confirmado repetido'],
    ],
  },

  {
    tabla: 'ref_tipos_incapacidad',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['NO', 'No'],
      ['SI', 'Sí'],
    ],
  },

  {
    tabla: 'ref_tipos_medicamento',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Medicamento con uso con registro sanitario'],
      ['02', 'Medicamento con uso como vital no disponible definido por INVIMA'],
      ['03', 'Preparación magistral'],
      ['04', 'Medicamento con uso no incluido en el registro sanitario (Listado UNIRS)'],
      ['05', 'Medicamento con autorización sanitaria de uso emergencia ASUE'],
    ],
  },

  {
    tabla: 'ref_formas_farmaceuticas',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['C28944', 'Crema'],
      ['C29167', 'Loción'],
      ['C29269', 'Enjuague'],
      ['C42887', 'Aerosol'],
      ['C42902', 'Cápsula de liberación retardada'],
      ['C42905', 'Tabletas de liberación retardada'],
      ['C42909', 'Gránulos efervescentes'],
      ['C42912', 'Elixir'],
      ['C42914', 'Emulsión inyectable'],
      ['C42916', 'Cápsula de liberación prolongada'],
      ['C42927', 'Tabletas de liberación prolongada'],
      ['C42932', 'Cinta adhesiva / película'],
      ['C42933', 'Gas'],
      ['C42938', 'Gránulos convencionales'],
      ['C42941', 'Goma'],
      ['C42942', 'Implante'],
      ['C42948', 'Geles y jaleas'],
      ['C42953', 'Líquido (diferentes a soluciones)'],
      ['C42966', 'Ungüento'],
      ['C42967', 'Pasta'],
      ['C42968', 'Sistemas transdérmicos'],
      ['C42969', 'Pellets'],
      ['C42983', 'Jabones y champú'],
      ['C42989', 'Espray'],
      ['C42993', 'Supositorio / óvulo'],
      ['C42994', 'Suspensión'],
      ['C42996', 'Jarabe'],
      ['C43000', 'Tintura'],
      ['C47913', 'Emplasto'],
      ['C47914', 'Tira'],
      ['C47915', 'Sistemas intrauterinos'],
      ['C64898', 'Espuma'],
      ['C64904', 'Cápsula cubierta dura'],
      ['C64909', 'Cápsula blanda'],
      ['C69031', 'Sistemas oculares'],
      ['C91199', 'Sistemas de anillos vaginales'],
      ['C91200', 'Sistemas'],
      ['COLFF001', 'Tabletas de liberación no modificada'],
      ['COLFF002', 'Polvos para no reconstituir'],
      ['COLFF003', 'Polvos para reconstituir'],
      ['COLFF004', 'Otras soluciones'],
      ['COLFF005', 'Otras emulsiones'],
      ['COLFF006', 'Cápsulas de liberación no modificada'],
      ['COLFF007', 'Cápsulas de liberación modificada'],
      ['COLFF008', 'Tabletas de liberación modificada'],
      ['COLFF009', 'Gránulos de liberación no modificada'],
      ['COLFF010', 'Gránulos de liberación modificada'],
    ],
  },

  // ── TABLAS NUEVAS ─────────────────────────────────────────────────────────

  {
    tabla: 'ref_causa_motivo_cons_ext',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['21', 'Accidente de trabajo'],
      ['22', 'Accidente en el hogar'],
      ['23', 'Accidente de tránsito de origen común'],
      ['24', 'Accidente de tránsito de origen laboral'],
      ['25', 'Accidente en el entorno educativo'],
      ['26', 'Otro tipo de accidente'],
      ['27', 'Evento catastrófico de origen natural'],
      ['28', 'Lesión por agresión'],
      ['29', 'Lesión auto infligida'],
      ['30', 'Sospecha de violencia física'],
      ['31', 'Sospecha de violencia psicológica'],
      ['32', 'Sospecha de violencia sexual'],
      ['33', 'Sospecha de negligencia y abandono'],
      ['34', 'IVE relacionado con peligro a la salud o vida de la mujer'],
      ['35', 'IVE por malformación congénita incompatible con la vida'],
      ['36', 'IVE por violencia sexual, incesto o por inseminación artificial o transferencia de óvulo fecundado no consentida'],
      ['37', 'Evento adverso en salud'],
      ['38', 'Enfermedad general'],
      ['39', 'Enfermedad laboral'],
      ['40', 'Promoción y mantenimiento de la salud - intervenciones individuales'],
      ['41', 'Intervención colectiva'],
      ['42', 'Atención de población materno perinatal'],
      ['43', 'Riesgo ambiental'],
      ['44', 'Otros eventos catastróficos'],
      ['45', 'Accidente de mina antipersonal - MAP'],
      ['46', 'Accidente de artefacto explosivo improvisado - AEI'],
      ['47', 'Accidente de munición sin explotar - MUSE'],
      ['48', 'Otra víctima de conflicto armado colombiano'],
    ],
  },

  {
    tabla: 'ref_causa_motivo_urg_proc',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['21', 'Accidente de trabajo'],
      ['22', 'Accidente en el hogar'],
      ['23', 'Accidente de tránsito de origen común'],
      ['24', 'Accidente de tránsito de origen laboral'],
      ['25', 'Accidente en el entorno educativo'],
      ['26', 'Otro tipo de accidente'],
      ['27', 'Evento catastrófico de origen natural'],
      ['28', 'Lesión por agresión'],
      ['29', 'Lesión auto infligida'],
      ['30', 'Sospecha de violencia física'],
      ['31', 'Sospecha de violencia psicológica'],
      ['32', 'Sospecha de violencia sexual'],
      ['33', 'Sospecha de negligencia y abandono'],
      ['34', 'IVE relacionado con peligro a la salud o vida de la mujer'],
      ['35', 'IVE por malformación congénita incompatible con la vida'],
      ['36', 'IVE por violencia sexual, incesto o por inseminación artificial o transferencia de óvulo fecundado no consentida'],
      ['37', 'Evento adverso en salud'],
      ['38', 'Enfermedad general'],
      ['39', 'Enfermedad laboral'],
      ['41', 'Intervención colectiva'],
      ['42', 'Atención de población materno perinatal'],
      ['43', 'Riesgo ambiental'],
      ['44', 'Otros eventos catastróficos'],
      ['45', 'Accidente de mina antipersonal - MAP'],
      ['46', 'Accidente de artefacto explosivo improvisado - AEI'],
      ['47', 'Accidente de munición sin explotar - MUSE'],
      ['48', 'Otra víctima de conflicto armado colombiano'],
    ],
  },

  {
    tabla: 'ref_cod_sexo',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['H', 'Hombre'],
      ['I', 'Indeterminado o Intersexual'],
      ['F', 'Mujer'],
    ],
  },

  {
    tabla: 'ref_cod_sexo_biologico',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Hombre'],
      ['02', 'Mujer'],
      ['03', 'Indeterminado o Intersexual'],
    ],
  },

  {
    tabla: 'ref_condicion_egreso',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Paciente con destino a su domicilio'],
      ['02', 'Paciente muerto'],
      ['03', 'Paciente derivado a otro servicio'],
      ['04', 'Referido a otra institución'],
      ['05', 'Contrareferido a otra institución'],
      ['06', 'Derivado o referido a hospitalización domiciliaria'],
      ['07', 'Derivado a servicio social'],
    ],
  },

  {
    tabla: 'ref_finalidad_tecnologia_salud',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['12', 'Detección temprana de enfermedad general'],
      ['13', 'Detección temprana de enfermedad laboral'],
      ['14', 'Protección específica'],
      ['15', 'Diagnóstico'],
      ['16', 'Tratamiento'],
      ['17', 'Rehabilitación'],
      ['18', 'Paliación'],
      ['19', 'Planificación familiar y anticoncepción'],
      ['20', 'Promoción y apoyo a la lactancia materna'],
      ['22', 'Atención para el cuidado preconcepcional'],
      ['23', 'Atención para el cuidado prenatal'],
      ['24', 'Interrupción voluntaria del embarazo'],
      ['25', 'Atención del parto y puerperio'],
      ['26', 'Atención para el cuidado del recién nacido'],
      ['27', 'Atención para el seguimiento del recién nacido'],
      ['28', 'Preparación para la maternidad y la paternidad'],
      ['29', 'Promoción de actividad física'],
      ['30', 'Promoción de la cesación del tabaquismo'],
      ['31', 'Prevención del consumo de sustancias psicoactivas'],
      ['32', 'Promoción de la alimentación saludable'],
      ['33', 'Promoción para el ejercicio de los derechos sexuales y derechos reproductivos'],
      ['34', 'Promoción para el desarrollo de habilidades para la vida'],
      ['35', 'Promoción para la construcción de estrategias de afrontamiento frente a sucesos vitales'],
      ['36', 'Promoción de la sana convivencia y el tejido social'],
      ['37', 'Promoción de un ambiente seguro y de cuidado y protección del ambiente'],
      ['38', 'Promoción del empoderamiento para el ejercicio del derecho a la salud'],
      ['39', 'Promoción para la adopción de prácticas de crianza y cuidado para la salud'],
      ['40', 'Promoción de la capacidad de la agencia y cuidado de la salud'],
      ['41', 'Desarrollo de habilidades cognitivas'],
      ['42', 'Intervención colectiva'],
      ['43', 'Modificación de la estética corporal fines estéticos'],
      ['44', 'Otra'],
    ],
  },

  {
    tabla: 'ref_tipo_nota',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['NA', 'Nota ajuste RIPS'],
      ['NC', 'Nota crédito'],
      ['ND', 'Nota débito'],
      ['RS', 'RIPS sin factura'],
    ],
  },

  {
    tabla: 'ref_tipo_os',
    columnas: ['codigo', 'descripcion'],
    filas: [
      ['01', 'Dispositivos médicos e insumos'],
      ['02', 'Traslados'],
      ['03', 'Estancias'],
      ['04', 'Servicios complementarios'],
      ['05', 'Honorarios'],
    ],
  },

  {
    tabla: 'ref_cod_servicio',
    columnas: ['codigo', 'descripcion'],
    filas: [
      [105, 'Cuidado intermedio neonatal'],
      [106, 'Cuidado intermedio pediátrico'],
      [107, 'Cuidado intermedio adultos'],
      [108, 'Cuidado intensivo neonatal'],
      [109, 'Cuidado intensivo pediátrico'],
      [110, 'Cuidado intensivo adultos'],
      [120, 'Cuidado básico neonatal'],
      [129, 'Hospitalización adultos'],
      [130, 'Hospitalización pediátrica'],
      [131, 'Hospitalización en salud mental'],
      [132, 'Hospitalización parcial'],
      [133, 'Hospitalización paciente crónico con ventilador'],
      [134, 'Hospitalización paciente crónico sin ventilador'],
      [135, 'Hospitalización en consumo de sustancias psicoactivas'],
      [138, 'Cuidado básico del consumo de sustancias psicoactivas'],
      [201, 'Cirugía de cabeza y cuello'],
      [202, 'Cirugía cardiovascular'],
      [203, 'Cirugía general'],
      [204, 'Cirugía ginecológica'],
      [205, 'Cirugía maxilofacial'],
      [207, 'Cirugía ortopédica'],
      [208, 'Cirugía oftalmológica'],
      [209, 'Cirugía otorrinolaringología'],
      [210, 'Cirugía oncológica'],
      [211, 'Cirugía oral'],
      [212, 'Cirugía pediátrica'],
      [213, 'Cirugía plástica y estética'],
      [214, 'Cirugía vascular y angiológica'],
      [215, 'Cirugía urológica'],
      [217, 'Otras cirugías'],
      [218, 'Cirugía endovascular neurológica'],
      [227, 'Cirugía oncológica pediátrica'],
      [231, 'Cirugía de la mano'],
      [232, 'Cirugía de mama y tumores tejidos blandos'],
      [233, 'Cirugía dermatológica'],
      [234, 'Cirugía de tórax'],
      [235, 'Cirugía gastrointestinal'],
      [237, 'Cirugía plástica oncológica'],
      [245, 'Neurocirugía'],
      [301, 'Anestesia'],
      [302, 'Cardiología'],
      [303, 'Cirugía cardiovascular'],
      [304, 'Cirugía general'],
      [306, 'Cirugía pediátrica'],
      [308, 'Dermatología'],
      [309, 'Dolor y cuidados paliativos'],
      [310, 'Endocrinología'],
      [311, 'Endodoncia'],
      [312, 'Enfermería'],
      [313, 'Estomatología'],
      [316, 'Gastroenterología'],
      [317, 'Genética'],
      [318, 'Geriatría'],
      [320, 'Ginecobstetricia'],
      [321, 'Hematología'],
      [323, 'Infectología'],
      [324, 'Inmunología'],
      [325, 'Medicina familiar'],
      [326, 'Medicina física y del deporte'],
      [327, 'Medicina física y rehabilitación'],
      [328, 'Medicina general'],
      [329, 'Medicina interna'],
      [330, 'Nefrología'],
      [331, 'Neumología'],
      [332, 'Neurología'],
      [333, 'Nutrición y dietética'],
      [334, 'Odontología general'],
      [335, 'Oftalmología'],
      [336, 'Oncología clínica'],
      [337, 'Optometría'],
      [338, 'Ortodoncia'],
      [339, 'Ortopedia y/o traumatología'],
      [340, 'Otorrinolaringología'],
      [342, 'Pediatría'],
      [343, 'Periodoncia'],
      [344, 'Psicología'],
      [345, 'Psiquiatría'],
      [346, 'Rehabilitación oncológica'],
      [347, 'Rehabilitación oral'],
      [348, 'Reumatología'],
      [354, 'Toxicología'],
      [355, 'Urología'],
      [356, 'Otras consultas de especialidad'],
      [361, 'Cardiología pediátrica'],
      [362, 'Cirugía de cabeza y cuello'],
      [363, 'Cirugía de mano'],
      [364, 'Cirugía de mama y tumores tejidos blandos'],
      [365, 'Cirugía dermatológica'],
      [366, 'Cirugía de tórax'],
      [367, 'Cirugía gastrointestinal'],
      [368, 'Cirugía ginecológica laparoscópica'],
      [369, 'Cirugía plástica y estética'],
      [370, 'Cirugía plástica oncológica'],
      [371, 'Otras consultas generales'],
      [372, 'Cirugía vascular'],
      [373, 'Cirugía oncológica'],
      [374, 'Cirugía oncológica pediátrica'],
      [375, 'Dermatología oncológica'],
      [377, 'Coloproctología'],
      [379, 'Ginecología oncológica'],
      [383, 'Medicina nuclear'],
      [384, 'Nefrología pediátrica'],
      [385, 'Neonatología'],
      [386, 'Neumología pediátrica'],
      [387, 'Neurocirugía'],
      [388, 'Neuropediatría'],
      [390, 'Oftalmología oncológica'],
      [391, 'Oncología y hematología pediátrica'],
      [393, 'Ortopedia oncológica'],
      [395, 'Urología oncológica'],
      [396, 'Odontopediatría'],
      [397, 'Medicina estética'],
      [406, 'Hematología oncológica'],
      [407, 'Medicina del trabajo y medicina laboral'],
      [408, 'Radioterapia'],
      [409, 'Ortopedia pediátrica'],
      [410, 'Cirugía oral'],
      [411, 'Cirugía maxilofacial'],
      [412, 'Medicina alternativa y complementaria - Homeopática'],
      [413, 'Medicina alternativa y complementaria - Ayurvédica'],
      [414, 'Medicina alternativa y complementaria - Tradicional China'],
      [415, 'Medicina alternativa y complementaria - Naturópática'],
      [416, 'Medicina alternativa y complementaria - Neuralterapéutica'],
      [417, 'Terapias alternativas y complementarias - Bioenergética'],
      [418, 'Terapias alternativas y complementarias - Terapia con filtros'],
      [419, 'Terapias alternativas y complementarias - Terapias manuales'],
      [420, 'Vacunación'],
      [421, 'Patología'],
      [422, 'Medicina alternativa y complementaria - Osteopática'],
      [423, 'Seguridad y salud en el trabajo'],
      [706, 'Laboratorio clínico'],
      [709, 'Quimioterapia'],
      [711, 'Radioterapia'],
      [712, 'Toma de muestras de laboratorio clínico'],
      [714, 'Servicio farmacéutico'],
      [715, 'Medicina nuclear'],
      [717, 'Laboratorio citologías cérvico-uterinas'],
      [728, 'Terapia ocupacional'],
      [729, 'Terapia respiratoria'],
      [731, 'Laboratorio de histotecnología'],
      [733, 'Hemodiálisis'],
      [734, 'Diálisis peritoneal'],
      [739, 'Fisioterapia'],
      [740, 'Fonoaudiología y/o terapia del lenguaje'],
      [742, 'Diagnóstico vascular'],
      [743, 'Hemodinamia e intervencionismo'],
      [744, 'Imágenes diagnósticas - ionizantes'],
      [745, 'Imágenes diagnósticas - no ionizantes'],
      [746, 'Gestión pre-transfusional'],
      [747, 'Patología'],
      [748, 'Radiología odontológica'],
      [749, 'Toma de muestras de cuello uterino y ginecológicas'],
      [1101, 'Atención del parto'],
      [1102, 'Urgencias'],
      [1103, 'Transporte asistencial básico'],
      [1104, 'Transporte asistencial medicalizado'],
      [1105, 'Atención prehospitalaria'],
    ],
  },

  {
    tabla: 'ref_unidad_min_dispensa',
    columnas: ['codigo', 'descripcion'],
    filas: [
      [1,'Ampolla'],[2,'Aplicador'],[3,'Bolsa'],[4,'Barra'],[5,'Perla'],
      [6,'Blíster'],[7,'Envase blíster'],[8,'Bloque'],[9,'Bolo'],[10,'Envase'],
      [11,'Caja'],[12,'Lata'],[13,'Frasco'],[14,'Cápsula'],[15,'Cartón'],
      [16,'Cartucho'],[17,'Estuche'],[18,'Película de PVC transparente de colores'],
      [19,'Unidades clínicas'],[20,'Recubrimiento'],[21,'Contenedor'],[22,'Recuento'],
      [23,'Copa'],[24,'Cilindro'],[25,'Vasos Dewar'],[26,'Dial pack'],[27,'Disco'],
      [28,'Dosis en envase'],[29,'Gotas'],[30,'Tambor - Bombo'],[31,'Película'],
      [32,'Generador'],[33,'Glóbulo'],[34,'Dilución homeopática'],[35,'Implante'],
      [36,'Inhalación'],[37,'Inhalador'],[38,'Inhalador, recarga'],[39,'Inserto'],
      [40,'Frasco'],[41,'Jarra'],[42,'Unidad inhibidora de calicreína'],[43,'Kit'],
      [44,'Pastilla'],[45,'Embalaje'],[46,'Paquete'],[47,'Balde'],[48,'Partes'],
      [49,'Parche'],[50,'Píldora (pellet)'],[51,'Pieza'],[53,'Unidades de presión'],
      [54,'Anillo'],[55,'Saturado'],[56,'Cuchara medidora'],[57,'Esponja'],
      [58,'Atomizador (spray)'],[59,'Centímetro cuadrado'],[61,'Tira'],
      [63,'Supositorio'],[64,'Hisopo'],[65,'Jeringa'],[66,'Tableta'],
      [67,'Tabminder'],[68,'Tampón'],[69,'Tanque'],[70,'Prueba'],[71,'Bandeja'],
      [72,'Troche'],[73,'Tubo'],[74,'Unidades'],[75,'Vial'],[76,'Oblea'],
      [77,'Termo'],[78,'Sobre'],[79,'Pluma'],[80,'Litro'],[81,'Óvulo'],
    ],
  },
];

// ─── Runner ───────────────────────────────────────────────────────────────────
async function run() {
  const conn = await testConnection();
  if (!conn.ok) { console.error('❌  BD:', conn.error); process.exit(1); }
  console.log(`✅  Conectado a ${conn.database}\n`);

  for (const seed of seeds) {
    try {
      await upsertAll(seed.tabla, seed.columnas, seed.filas);
    } catch (err) {
      console.error(`  ❌  ${seed.tabla}: ${err.message}`);
    }
  }

  console.log('\n🎉  Seeds SISPRO completos.');
  await pool.end();
}

run();
